---
- name: Create Ansible user
  hosts: all
  become: yes

  tasks:
    - name: Create user
      tags: create_user
      user:
        name: ansible
        group: root
        shell: /bin/bash
        state: present
        #state: absent
        #remove: true

    - name: Add SSH key
      tags: create_user
      authorized_key:
        user: ansible
        key: "{{ lookup('file', '/$HOME/.ssh/id_rsa.pub') }}"
        # key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDoDnegeY5v982PUGogdBs+8pYbTbGDvdDx8KYLeSWOUl639b/lzGGC+PwAkd8/l/YqghRqR/8u1XyXSHQKBblike2dWGB57tj/Yf+933W3yUtjlSVkptguPcVurxBlHe/Vyq0RlxTWutaJC5vZ9P5jIQl8h2cCfq5z56OuASk30+YTZ4DdDonz1IVsXyokAXjEGwrlFKuOn7pbGBVUoGrMdJNpAsGxo1j0BG+UF3oMJwyh++VNaCPrgQOpQKUWtJN5ymOK5gqRmjZWGUs+3oDDuSglCQXFWxiOhZF7DZECtU6yD9/uNSWeg2ZZQQbL8JQL1A+6182nL9UJOEYbGuFR gurkirat@ssh-server"

    - name: Add sudoers file for ansible user
      tags: create_user
      copy:
        # content: "ansible ALL=(ALL) NOPASSWD:ALL"
        src: ansible_sudoers
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: '0440'