- name: Update repository index
  hosts: all
  become: true
  tags: update_repo, always
  # pre_tasks:
  #   - name: Update repository index for RedHat based systems
  #     package:
  #       update_cache: yes
  #     when: ansible_distribution in ["RedHat", "Fedora"]

- name: Executing tasks from base role
  hosts: all
  become: true
  roles:
    - base

- name: Executing tasks from webserver role
  hosts: FEDORA
  become: true
  roles:
    - webserver

- name: Executing tasks from workstation role
  hosts: WORKSTATION
  become: true
  roles:
    - workstation
